# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-wsl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: download-ubuntu-wsl-distributiion
        shell: powershell # $output = "$PSScriptRoot\Ubuntu.appx"
        run: |
          $url = "https://aka.ms/wsl-ubuntu-1804"
          $output = ".\Ubuntu.appx"
          $start_time = Get-Date
          (New-Object System.Net.WebClient).DownloadFile($url, $output)
          Rename-Item .\Ubuntu.appx .\Ubuntu.zip
          Expand-Archive .\Ubuntu.zip .\Ubuntu          
          Get-ChildItem -Path .\
          Get-ChildItem -Path .\Ubuntu
      - name: test-wsl
        shell: powershell
        run: |
          Get-ChildItem -Path .\
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
          .\Ubuntu\ubuntu1804.exe
          root
          -p password
          echo "i am g$USER"
        # wsl -u root -d Ubuntu-18.04
        # echo "i am $USER"
        # wsl -u root -d Ubuntu-18.04 -- apt-get update && apt-get install -y curl
        # wsl -u root -d Ubuntu-18.04 -- curl -L ifconfig.me


# Get-ChildItem -Path .\
# Get-ChildItem -Path .\Ubuntu
# wsl --set-default-version 2
# .\Ubuntu\ubuntu1804.exe install --root
# wsl -u root -d Ubuntu-18.04 -- echo "I am g$USER"
# wsl -u root -d Ubuntu-18.04 -- apt-get update && apt-get install -y curl
# wsl -u root -d Ubuntu-18.04 -- curl ifconfig.me
