# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-wsl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-wsl
        shell: cmd
        run: | 
          wsl
